name: rebound
version: 0.0.2-dev
description: >
  A Dart wrapper for ReboundJS. Rebound spring models can be used to
  create animations that feel natural by introducing real world physics
  to your application.
homepage: https://github.com/danschultz/rebound.dart
dependencies:
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
